### ISSUE TITLE
its literal fucking malware

### ISSUE THREAD

**Issue by crazycrystals** [oureveryday/Steam-auto-crack#26]
https://analyze.intezer.com/analyses/70f9696c-f991-4082-92c1-340defb6e7c5/sub/658ee885-33c2-4392-9916-012ec2e915d8

Explain this and I might run it.

**Comment by oureveryday** [comment]
Download and install autohotkey and download https://github.com/oureveryday/Steam-auto-crack/archive/refs/heads/master.zip
Direct run src\SteamAutoCrack.ahk
Source code is open and no virus.
Also making tool new version with c# that won't get False Positive.

**Comment by oureveryday** [comment]
The false prositive should gone in 3.0 release.
