### ISSUE TITLE
The configuration method of Goldberg Emulator has changed

### ISSUE THREAD

**Issue by lls7890** [oureveryday/Steam-auto-crack#58]
The configuration method of the new version of Goldberg Emulator has changed. It no longer uses force_steamid.txt to force the steamID.

**Comment by oureveryday** [comment]
Can you tell me how did it changed? Is there any new docs?

**Comment by lls7890** [comment]
https://github.com/otavepto/gbe_fork/releases/download/release-2024_5_5/emu-win-release.7z
in /steam_settings.EXAMPLE/configs.user.EXAMPLE.ini

**Comment by oureveryday** [comment]
Will look into it later.

**Comment by oureveryday** [comment]
This is updated in version 3.4.1.0.
